# Generated by Django 5.1.4 on 2025-03-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tabel Gedung',
            },
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tabel Jurusan',
            },
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('no_ktp', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=12)),
                ('alamat', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('id_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namaproyek.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Tabel Dosen',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('no_ktp', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=12)),
                ('alamat', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('id_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namaproyek.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Tabel Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('lantai', models.IntegerField()),
                ('id_gedung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namaproyek.gedung')),
            ],
            options={
                'verbose_name_plural': 'Tabel Ruang',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('waktu_1', models.TimeField()),
                ('waktu_2', models.TimeField()),
                ('tanggal', models.DateField()),
                ('id_dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namaproyek.dosen')),
                ('id_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namaproyek.jurusan')),
                ('id_ruang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namaproyek.ruang')),
            ],
            options={
                'verbose_name_plural': 'Tabel Jadwal',
            },
        ),
    ]
