# Generated by Django 5.1.4 on 2025-03-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaproyek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('sks', models.IntegerField()),
                ('id_jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namaproyek.jurusan')),
            ],
            options={
                'verbose_name_plural': 'Tabel Matkul',
            },
        ),
        migrations.AddField(
            model_name='jadwal',
            name='id_matkul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namaproyek.matkul'),
        ),
    ]
